# Generated by Django 2.1.5 on 2019-11-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengepost', '0002_remove_challengepost_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengecomment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
