# Generated by Django 2.1.5 on 2019-05-28 21:55

from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playin_time', models.CharField(max_length=100, verbose_name='출장 시간')),
                ('FGP', models.CharField(max_length=50, verbose_name='야투 성공률')),
                ('T3PP', models.CharField(max_length=50, verbose_name='3점 야투 성공률')),
                ('FTP', models.CharField(max_length=50, verbose_name='자유투 성공률')),
                ('PPG', models.CharField(max_length=50, verbose_name='게임 평균 득점')),
                ('RPG', models.CharField(max_length=50, verbose_name='게임 평균 리바운드')),
                ('APG', models.CharField(max_length=50, verbose_name='게임 평균 어시스트')),
                ('BPG', models.CharField(max_length=50, verbose_name='게임 평균 블락')),
                ('name', models.CharField(max_length=100, verbose_name='풀네임')),
                ('back_number', models.CharField(max_length=100, verbose_name='선수 등 번호')),
                ('position', models.CharField(max_length=5, verbose_name='선수 포지션')),
                ('first_name', models.CharField(max_length=50, verbose_name='선수 이름')),
                ('last_name', models.CharField(max_length=50, verbose_name='선수 성씨')),
                ('height', models.CharField(max_length=100, verbose_name='선수 키')),
                ('weight', models.CharField(max_length=100, verbose_name='선수 무게')),
                ('born', models.CharField(max_length=50, verbose_name='선수 생년월일')),
                ('hometown', models.CharField(max_length=50, verbose_name='선수 고향')),
                ('nba_debut', models.CharField(max_length=50, verbose_name='데뷔 년도')),
                ('image', models.ImageField(blank=True, default=True, null=True, upload_to=members.models.player_path, verbose_name='선수 사진')),
            ],
            options={
                'verbose_name': 'NBA 선수',
                'verbose_name_plural': 'NBA 선수 목록',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='팀 이름')),
                ('team_image', models.ImageField(blank=True, default=True, null=True, upload_to=members.models.team_path, verbose_name='팀 사진')),
            ],
            options={
                'verbose_name': 'NBA 팀',
                'verbose_name_plural': 'NBA 팀 목록',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Team'),
        ),
    ]
