# Generated by Django 2.1.5 on 2019-03-25 00:54

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='작성 글')),
                ('created_at', models.DateTimeField(verbose_name='작성 날')),
                ('updated_at', models.DateTimeField(verbose_name='수정 날짜')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playin_time', models.CharField(max_length=100, verbose_name='출장 시간')),
                ('FGP', models.CharField(max_length=50, verbose_name='야투 성공률')),
                ('T3PP', models.CharField(max_length=50, verbose_name='3점 야투 성공률')),
                ('FTP', models.CharField(max_length=50, verbose_name='자유투 성공률')),
                ('PPG', models.CharField(max_length=50, verbose_name='게임 평균 득점')),
                ('RPG', models.CharField(max_length=50, verbose_name='게임 평균 리바운드')),
                ('APG', models.CharField(max_length=50, verbose_name='게임 평균 어시스트')),
                ('BPG', models.CharField(max_length=50, verbose_name='게임 평균 블락')),
                ('name', models.CharField(max_length=100, verbose_name='풀네임')),
                ('back_number', models.CharField(max_length=100, verbose_name='선수 등 번호')),
                ('position', models.CharField(max_length=5, verbose_name='선수 포지션')),
                ('first_name', models.CharField(max_length=50, verbose_name='선수 이름')),
                ('last_name', models.CharField(max_length=50, verbose_name='선수 성씨')),
                ('height', models.CharField(max_length=100, verbose_name='선수 키')),
                ('weight', models.CharField(max_length=100, verbose_name='선수 무게')),
                ('born', models.CharField(max_length=50, verbose_name='선수 생년월일')),
                ('hometown', models.CharField(max_length=50, verbose_name='선수 고향')),
                ('nba_debut', models.CharField(max_length=50, verbose_name='데뷔 년도')),
                ('image', models.ImageField(blank=True, default=True, null=True, upload_to=members.models.player_path, verbose_name='선수 사진')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='작성 글')),
                ('created_at', models.DateTimeField(verbose_name='생성 날짜')),
                ('updated_at', models.DateTimeField(verbose_name='수정 날짜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signature_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ManyToManyField(blank=True, null=True, to='members.Player')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='팀 이름')),
                ('team_image', models.ImageField(blank=True, default=True, null=True, upload_to=members.models.team_path, verbose_name='팀 사진')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Team'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='player',
            field=models.ManyToManyField(blank=True, null=True, to='members.Player'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
