# Generated by Django 2.1.2 on 2019-01-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_team'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='team',
            managers=[
            ],
        ),
    ]
