# Generated by Django 2.1.5 on 2019-05-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190528_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='_html',
            field=models.TextField(blank=True, verbose_name='태그가 html화 된 댓글 내용'),
        ),
        migrations.AddField(
            model_name='post',
            name='_html',
            field=models.TextField(blank=True, verbose_name='태그가 html화 된 댓글 내용'),
        ),
    ]
