# Generated by Django 2.1.5 on 2019-05-24 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190524_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.TextField(default=django.utils.timezone.now, max_length=50, verbose_name='게시글 태그'),
            preserve_default=False,
        ),
    ]
