# Generated by Django 2.1.5 on 2019-08-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190812_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='commented', to='posts.Post', verbose_name='포스트'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='comment_set', related_query_name='comments', to='posts.HashTags'),
        ),
    ]
